---
title: "Exemplos de Analise de Clusters"
output:
  html_document:
    df_print: paged
---

#Base de Dados

```{r}
# Designar work directory.
getwd()
options(encoding = 'UTF-8')
```

```{r}
# Ler os dados do arquivo Excel no work directory.
#install.packages("readxl")
getwd()
library(readxl)
ATIBAIA <- read_xlsx("data", sheet = "ATIBAIA", col_names = TRUE)
```

#Estudo e Avaliacao dos Dados

```{r}
# Mapear os tipos dos dados das colunas da tabela importada.
sapply(ATIBAIA, class)
# Sumarizar as caracter?sticas univariadas dos dados da tabela importada.
summary(ATIBAIA)
# Repare que as vari?veis biling, estac e ti est?o sendo erroneamente sendo tratadas como num?ricas, quando na verdade s?o fatores.
```

```{r}
# Mudar o tipo das vari?veis biling, estac e ti para factor.
ATIBAIA$biling=as.factor(ATIBAIA$biling)
ATIBAIA$estac=as.factor(ATIBAIA$estac)
ATIBAIA$ti=as.factor(ATIBAIA$ti)
# Refazer a sumarizacao das caracter?sticas univariadas dos dados da tabela importada, agora com os tipos das colunas corrigidos.
summary(ATIBAIA)
```

```{r}
# Selecionar somente as vari?veis drivers de clustering (filial n?o ? porque ? apenas o nome da filial, aval_global n?o ? porque ? uma composi??o das outras vari?veis, e idade tamb?m n?o ? porque n?o ? um fator caracterizador relevante).
ATIBAIA_drivers = ATIBAIA[ , -c(1,2,9)]
```

#Algoritmos Nativos do R (patote 'stats')

##An. de Clusters POR PARTI??O: K-Means

```{r}
# Preparando dados, transformando tudo para tipo num?rico e colocando as colunas em escala.
ATIBAIA_drivers_num <- ATIBAIA_drivers
ATIBAIA_drivers_num$biling = as.numeric(ATIBAIA_drivers_num$biling)
ATIBAIA_drivers_num$estac = as.numeric(ATIBAIA_drivers_num$estac)
ATIBAIA_drivers_num$ti = as.numeric(ATIBAIA_drivers_num$ti)

ATIBAIA_drivers_num_z <- as.data.frame(lapply(ATIBAIA_drivers_num, scale))
```

```{r}
# Calculando a correlacao entre as vari?veis. Deve-se tomar o cuidado de que n?o hajam grandes correlacoes entre as vari?veis, pois estar?amos considerando a mesma informacao repetidas vezes, aumentando o "peso" daquela informacao na formacao dos clusters.
cor(ATIBAIA_drivers_num_z)
# Ok, n?o existem grandes correlacoes.
```

```{r}
# A funcao mais utilizada para operacionalizar o K-Means ? a kmeans, nativa do R vinculada ? biblioteca stats, tamb?m nativa do R. Por ser uma biblioteca nativa, n?o h? necessidade de carregar a biblioteca pois a mesma j? ? naturalmete carregada.
KMeans_clustering_k3 <- kmeans(ATIBAIA_drivers_num_z, 4, nstart = 100)
KMeans_clustering_k3
```

```{r}
# Vetor de clusters finais.
KMeans_clustering_k3$cluster
```

```{r}
# Centr?ides dos clusters.
KMeans_clustering_k3$centers
```

```{r}
# Soma total de distancias quadr?ticas (Total Sum of Squares).
KMeans_clustering_k3$totss
```

```{r}
# Soma de distancias quadr?ticas internas a cada cluster (Whithin Sum of Squares).
KMeans_clustering_k3$withinss
```

```{r}
# Soma total de distancias quadr?ticas internas a cada cluster (Total Whithin Sum of Squares).
KMeans_clustering_k3$tot.withinss
```

```{r}
# Soma total de distancias quadr?ticas entre observacoes de clusters diferentes (Between Sum of Squares).
KMeans_clustering_k3$betweenss
```

```{r}
# Tamanho dos clusters.
KMeans_clustering_k3$size
```

```{r}
# Itera?oes para que se chegasse ao resultado final.
KMeans_clustering_k3$iter
```

```{r}
# Indicacao de se houve alguma falha na execu??o do algoritmo.
KMeans_clustering_k3$ifault
```

```{r}
# Carregar pacote fpc (Flexible Procedures for Clustering), que possui uma s?rie de fun??es para analise de clusters.
library(fpc)
# Utilizar a funcao plotcluster do pacote fpc, que imprime o grafico espacial nas duas componentes principais mais relevantes.
plotcluster(ATIBAIA_drivers_num_z, KMeans_clustering_k3$cluster)
# Nota-se que os grupos est?o bem separados, o que ? um bom sinal.
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_cluster(list(data = ATIBAIA_drivers_num_z, cluster = KMeans_clustering_k3$cluster),  show.clust.cent = T)

```

```{r}
# Calcular a matriz de distancias.
?dist
ATIBAIA_drivers_num_z_dist <- dist(ATIBAIA_drivers_num_z, method = "euclidean")
ATIBAIA_drivers_num_z_dist
```

```{r}
# Utilizar a funcao cluster.stats da library fpc para uma lista maior de m?tricas da solucao de clusters encontrada.
library(fpc)
?cluster.stats
cluster.stats(ATIBAIA_drivers_num_z_dist, KMeans_clustering_k3$cluster)
```

# Algoritmos do Pacote 'clusters'

```{r}
# O pacote clusters tem uma s?rie de fun??es (daisy, que calcula a matriz de dist?ncia por Gower) e algoritmos (AGNES e DIANA, por exemplo) de analise de clusters.
#install.packages("cluster")
library(cluster)

# Padronizar as vari?veis e calcular a matriz de distancias por m?trica de Gower.
md = daisy(ATIBAIA_drivers)

md

```

##An. de Clusters POR PARTI??O: K-Medoid

```{r}
# Usa-se a funcao pam (Partitioning Around Medoids) do pacote cluster.
library(cluster)
KMedoid_clustering <- pam(md, k = 3, diss = TRUE)
KMedoid_clustering
```


``` {r}
library(factoextra)
fviz_cluster(list(data = ATIBAIA_drivers_num_z, cluster = KMedoid_clustering$clustering),  show.clust.cent = T)
```


```{r}
# A entrada para a funcao pam pode ser tanto a matriz de distancias (caso anterior), quanto a matriz de observacoes (x) por vari?veis (y) (como no caso abaixo). Deve-se alterar o par?metro diss para FALSE).
library(cluster)
KMedoid_clustering <- pam(ATIBAIA_drivers_num_z, k = 3, diss = FALSE)
KMedoid_clustering
```

```{r}
# Imprimir os medoids finais.
KMedoid_clustering$medoids
```

```{r}
# Imprimir os ids dos medoids finais.
KMedoid_clustering$id.med
```

```{r}
# Vetor de clusters de cada observacao.
KMedoid_clustering$clustering
```

```{r}
# funcao objetivo do metodo de constru??o e swap (algoritmos de otimizacao que s?o executados pr? K-Medoid para que a escolha inicial de medoids seja melhorada.
KMedoid_clustering$objective
```

```{r}
# Indicacao se algum dos clusters pode ser classificado como isolado (quando o di?metro ? maior que a separacao de clusters ou outras relacoes desfavor?veis de m?tricas).
KMedoid_clustering$isolation
```

```{r}
# Informacoes de dist?ncia.
KMedoid_clustering$clusinfo
```

```{r}
# Informacao de silhouette.
KMedoid_clustering$silinfo
```

```{r}
# Matriz de distancias de distancias.
KMedoid_clustering$diss
```

```{r}
# Chamada de funcao originadora.
KMedoid_clustering$call
```

```{r}
# Jeito mais f?cil de imprimir o grafico de silhouette.
plot(KMedoid_clustering)
```

```{r}
# Outra maneira de obter dados de silhouette e imprimir o grafico correspondente.
library(cluster)
sil=silhouette(KMedoid_clustering, md)
head(sil[,1:3])
plot(sil, cex=.6, border = 1, col = "lightblue")
```

```{r}
# Utilizar a funcao cluster.stats da library fpc para uma lista maior de m?tricas da solucao de clusters encontrada.
library(fpc)
?cluster.stats
cluster.stats(ATIBAIA_drivers_num_z_dist, KMedoid_clustering$cluster)
```

##An. de Clusters HIER?RQUICOS: AGNES

```{r}
# Usa-se a funcao agnes do pacote cluster.
library(cluster)
agnes_clustering <- agnes(md, diss = TRUE, method = "complete")
agnes_clustering
```

```{r}
# Imprime a ordem das observacoes, guardadas para facilitar a impressao do dendograma.
agnes_clustering$order
```

```{r}
# Imprime a altura de aglomeracao para as observacoes conforme vao acontecendo.
agnes_clustering$height
```

```{r}
agnes_clustering$ac
```

```{r}
agnes_clustering$merge
```

```{r}
agnes_clustering$diss
```

```{r}
agnes_clustering$call
```

```{r}
agnes_clustering$method
```

```{r}
plot(agnes_clustering)
```

```{r}
agnes_clustering_k3 <- cutree(agnes_clustering, k = 3)
agnes_clustering_k3
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_dend(agnes_clustering, k=3)
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_cluster(list(data = ATIBAIA_drivers_num_z, cluster = agnes_clustering_k3),  show.clust.cent = F)
```

```{r}
# Utilizar a funcao cluster.stats da library fpc para uma lista maior de m?tricas da solucao de clusters encontrada.
library(fpc)
?cluster.stats
cluster.stats(ATIBAIA_drivers_num_z_dist, agnes_clustering_k3)
```

##An. de Clusters HIER?RQUICOS: DIANA

```{r}
library(cluster)
diana_clustering <- diana(md, diss = TRUE)
diana_clustering
```

```{r}
# Imprime a ordem das observacoes, guardadas para facilitar a impressao do dendograma.
diana_clustering$order
```

```{r}
# Imprime a altura de aglomeracao para as observacoes conforme vao acontecendo.
diana_clustering$height
```

```{r}
# Imprime o coeficiente de 
diana_clustering$dc
```

```{r}
diana_clustering$merge
```

```{r}
diana_clustering$diss
```

```{r}
plot(diana_clustering)
```

```{r}
diana_clustering_k3 <- cutree(diana_clustering, k = 3)
diana_clustering_k3
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_dend(agnes_clustering, k=3)
```

```{r}
#install.packages("factoextra")
library(factoextra)
fviz_cluster(list(data = ATIBAIA_drivers_num_z, cluster = agnes_clustering_k3),  show.clust.cent = F)
```

```{r}
# Utilizar a funcao cluster.stats da library fpc para uma lista maior de m?tricas da solucao de clusters encontrada.
library(fpc)
?cluster.stats
cluster.stats(ATIBAIA_drivers_num_z_dist, diana_clustering_k3)
```
