---
title: "Exploração dos Clusters"
output:
  html_document:
    df_print: paged
date: "Outubro de 2019"
---

```{r setup_evaluation, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos =  "h")
knitr::opts_knit$set(root.dir = "./")

# data exploration libraries
library(tibble)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)

# clusters analysis libraries
library(fpc)
library(factoextra)
library(cluster)
library(ggcorrplot)
library(reshape2)

# plotting libraries
library(ggplot2)
library(plotly)
library(ggthemes)
```

```{r scripts_evaluation, include=FALSE}
# loading required steps before performing the analysis
source("../src/util/auxiliary_functions.R")
```

# Carregando a base de dados processada

Carregamos a base de dados alvo, previamente tratada durante os passos explicados na fase de **Data Preparation** (preparação de dados). 

```{r data_load, echo=TRUE}
target_data <- readRDS('../data/processed/target_dataset.rds')
```

*******************************************************************************

# Tópico

## Sub-tópico

Descrever.

```{r generating_naive_model, echo=TRUE, out.width='100%'}
# to-do
```

